### ISSUE TITLE
There must be a matching reward in order for a vote to count

### ISSUE THREAD

**Issue by lagnat** [minecrafter/SuperbVote#12]
If I'm understanding this correctly, a vote will not count if there's no matching reward.  Reverse these two blocks or remove the check?

```
            case PROCESS_VOTE:
                if (preVoteEvent.getVoteRewards().isEmpty()) {
                    throw new RuntimeException("No vote reward found for '" + vote + "'");
                }

                if (!vote.isFakeVote() || SuperbVote.getPlugin().getConfig().getBoolean("votes.process-fake-votes")) {
                    SuperbVote.getPlugin().getVoteStorage().issueVote(vote);
                }

```

**Comment by minecrafter** [comment]
A reward is required. While SuperbVote could just record votes, it's not very useful when used like that. If you don't want to give a reward, make that explicit.

**Comment by lagnat** [comment]
The reward comes after 10 votes, lets say.  As it stands, Im forced to have an if: {} reward that does nothing just to prevent the exception.  It seems somewhat arbitrary to force a reward for each vote.

**Comment by astei** [comment]
As an update to this issue:

Yes, SuperbVote is designed to have a default award (and due to my continued lack of interest in Minecraft, I don't have the motivation to refactor the plugin in any major way). _However_, you don't have to execute any commands (or even broadcast a message).
