### ISSUE TITLE
Superbvote doesnt give rewards to players

### ISSUE THREAD

**Issue by Chumb3x** [minecrafter/SuperbVote#132]
Superbvote doesnt give rewards to players. Here is my config file. https://pastebin.com/ENN5G4Sk

**Comment by AlexanderOFGR** [comment]
- if:
      default: true
    commands:
    - lootcrate give %player% 341 1
    - give %player% diamond 2
    player-message: "&eThanks for voting for us on %service%, you have been rewarded with 1 Voting Key."
    broadcast-message: "&e%player% has voted for us on %service% and was rewarded with 1 Voting Key!"
    
    This should fix it ;) (By the way, make sure formatting is right!)
