### ISSUE TITLE
Mojang API rate-limiting issues

### ISSUE THREAD

**Issue by cloakfox** [minecrafter/SuperbVote#18]
Error: https://hastebin.com/afetuvubef.pl
Using PaperSpigot 1.12

**Comment by minecrafter** [comment]
This isn't an issue with PlotSquared. It's Mojang API rate-limiting.

**Comment by minecrafter** [comment]
Probably resolved now, but requires further testing.

**Comment by astei** [comment]
Fully fixed in the 0.4 beta, which relies on the Mojang usercache (through Bukkit)
