### ISSUE TITLE
Not Working in 1.8

### ISSUE THREAD

**Issue by Swamfirehow1390** [minecrafter/SuperbVote#24]
Hai I Have problem setting it up in 1.8, it works in 1.9 but when i change the version to 1.8(due to a bug) it stops working

**Comment by minecrafter** [comment]
Non-specific issue. This should really be asked on [Spigot](https://www.spigotmc.org/threads/superbvote.89075/) anyway.

Please make sure to include more information, such as a stack trace (if applicable) and a description of the issue you are having.
