### ISSUE TITLE
my player doenst get the reward 

### ISSUE THREAD

**Issue by mrkawalski** [minecrafter/SuperbVote#28]
votifier config:
https://pastebin.com/8uqKBkrA

superbvote config:
https://pastebin.com/gAq6vHeF

**Comment by minecrafter** [comment]
Non-specific issue. This should really be asked on [Spigot](https://www.spigotmc.org/threads/superbvote.89075/) anyway.

Please make sure to include more information, such as a stack trace (if applicable) and a description of the issue you are having.
