### ISSUE TITLE
Random error

### ISSUE THREAD

**Issue by RainOfPain125** [minecrafter/SuperbVote#36]
https://pastebin.com/QLQ2H8N5

git-Paper-1320

0.4-BETA

Plugins (74): ActionAnnouncer, AdvancedBan, AreaShop, ArrowTrails, Auctions, Autorank, AutoSaveWorld, BlowableObsidians, BuycraftX, CFD, Chairs, ChatFeelings, ChatItem, ChestRestock, Citizens, ColoredAnvils, CombatLogX, CompatNoCheatPlus, CoreProtect, CrazyCrates, CrazyEnvoy, DailyBonus, DeluxeJoin, DiscordSRV, EpicRename, Essentials, EssentialsChat, eZProtector, FactionChat, Factions, FactionsFly, HolographicDisplays, HolographicScoreboard, InfoBook, InventoryFull, LimitCrafting, LuckPerms, MassiveBooks, MassiveCore, mcMMO, mcMMOAction, MessageAnnouncer, MobArena, Multiverse-Core, NametagEdit, NoCheatPlus, NoPlugins, OldCombatMechanics, Orebfuscator4, PerWorldInventory, PlayerHeads, PluginLibrary, PowerNBT, ProtocolLib, React, ServerListPlus, ShopGUIPlus, ShulkerBlock, SilkSpawners, SilkSpawnersShopAddon, SimpleBackup, SuperbVote, SuperTrails, SuperVanish, Tablist, TitleManager, Trading, Vault, Votifier, WarningCategories, Wild, WorldBorder, WorldEdit, WorldGuard

**Comment by minecrafter** [comment]
This will be resolved with 0.4's final release, but for now, create `plugins/SuperbVote/db_version.yml` with the text `db_version: 2`.
