### ISSUE TITLE
superbvotes placeholder cannot be display and leaderheads cannot update the stats

### ISSUE THREAD

**Issue by eric2788** [minecrafter/SuperbVote#40]
PlaceholderAPI and Leaderheads do appear an error about superbvotes
PlaceholderAPI: https://pastebin.com/R3Ep55Pb
 - bug: cannot display the placeholder stats
Leaderheads: https://pastebin.com/AduG75Ag
 - bug: cannot update the leader stats
I just wanna know whether these errors are regarding on them or the superbvote plugin
three of them are the latest version i have installed and the expansion of superbvote is also the latest version
my server version is 1.12.2

**Comment by astei** [comment]
I can't fix PlaceholderAPI or LeaderHeads, and I'm not in the position to revert the API changes I made to SuperbVote to make 0.4 possible.

Please ask clip and RobiRami to update their plugins.
