### ISSUE TITLE
got an error about superbvote

### ISSUE THREAD

**Issue by eric2788** [minecrafter/SuperbVote#41]
hello, i got one error while starting the server
error log: https://pastebin.com/qyg342MZ
i have tried regenerating the config.yml or empty the database but it still appear on my log
superbvote: is 0.4.1 latest
server version is 1.12.2
nuvotifier version is 2.3.6

**Comment by astei** [comment]
Can you paste your SuperbVote `config.yml`(s)?

**Comment by eric2788** [comment]
oh, you mean only one config.yml can with read-only: false
another should be set to true?
btw my config.yml
`# SuperbVote configuration
# A superb vote plugin made by Tux.
#
# https://minecraft.minimum.io/wiki/SuperbVote

# Database configuration.
# Currently supported: "json".
storage:
  database: mysql
  json:
    file: votes.json
  mysql:
    host: 127.0.0.1
    port: 3306
    username: user
    password: 'pass1ord'
    database: minecraft
    table: votes
    read-only: false

# General vote configuration.
votes:
  # At least this many seconds need to pass before allowing another vote (per-service). This will apply per service.
  # Default: 3600 seconds (1 hour)
  cooldown-per-service: 86400

  # Whether or not to treat the server as online-mode. This is mostly required for BungeeCord setups.
  force-online-mode: false

# Rewards. This is the main section you will need to edit. Ordering is important.
rewards:
  # Example of matchers.
  - if: {}
    commands:
    - money deposit %player% 100
    - points give %player% 50
    player-message: "&4thankyou"
    broadcast-message: ""
# Whether or not players need to be online to vote. If set, offline player votes are queued for when the player next logs in.
require-online: false

# Broadcast settings:
broadcast:
  # Should we broadcast votes at all?
  enabled: false

  # Should we tell players if they voted?
  message-player: true

  # Should we broadcast queued votes?
  queued: true

# Vote command.
vote-command:
  enabled: true
  text: |-
    &4// &7vote here!
    &4// &ehttp://minecraft-mp.com/

# Vote reminder.
vote-reminder:
  message: "&4vote us!"
  on-join: true
  repeat: 300

# Controls the /sv <top/leaderboard> command.
leaderboard:
  # Supported: text, scoreboard
  display: text
  # The text format supports pagination.
  text:
    per-page: 10
    header: "&c&m         &r&b top voter &r&c&m         &r"
    entry: "&e%num%. &7%player% (&e%votes%&7 v)"

  # Control the scoreboard.
  scoreboard:
    title: toper
    max: 10

# Control top player signs.
top-player-signs:
  format:
  - "#%num%"
  - ""
  - "%player%"
  - "&l%votes% &rv"`

**Comment by astei** [comment]
Yes. If you're using multiple servers sharing the same DB, you _must_ set `read-only: true` on all but one server (which will record the vote).

For those setups, 079c099 fixes the problem. It necessities a new release of SuperbVote.

**Comment by eric2788** [comment]
well, so I just meed to wait for the next update release?

**Comment by astei** [comment]
Yes.

**Comment by astei** [comment]
Closing because this will be fixed in a future release.
