### ISSUE TITLE
API?

### ISSUE THREAD

**Issue by CodaMacroft** [minecrafter/SuperbVote#42]
It would be cool if I could check the votes for a specific Player in my plugin as well as get all the votes that are stored overall from an API so I could use it in my Plugin.

**Comment by CodaMacroft** [comment]
Never mind. Just released you had the code released. Might want to tell people on the spigot page that there is an API that they can use and kinda how to use it.

**Comment by CodaMacroft** [comment]
realized*

**Comment by astei** [comment]
I currently don't have problems to publish a stable API. Everything in the `io.minimum.minecraft.superbvote` can be changed at any time. However, the only substantive change I've made so far is was in 0.4 when I did some refactoring.

Eventually there may be a time when the plugin internals are completely overhauled, but that day is unlikely to come for a long time.
