### ISSUE TITLE
Votes on 1 server only

### ISSUE THREAD

**Issue by AmazedMender16** [minecrafter/SuperbVote#45]
When using the same database superbvote caches for all servers. when a user joins a server they get the rewards on all servers.. anyway to disable this? so they only get it on 1 server?

I did setup to allow offline voting, but shouldn't it be when a user joins the server they receive their items there. when they switch servers they shouldn't get the items there aswell.

**Comment by astei** [comment]
Assuming you're using NuVotifier, you might want to investigate the [BungeeCord NuVotifier configuration](https://github.com/parallelblock/NuVotifier/blob/master/bungeecord/src/main/resources/bungeeConfig.yml#L28).

SuperbVote can't tell if a vote is forwarded or not - it'll process any vote it gets as configured. You need to configure your vote forwarder manually.

While I _may_ consider adding more "smart" configuration options in a future release, those aren't planned to happen in the near future.
