### ISSUE TITLE
Vote Reminder Issue

### ISSUE THREAD

**Issue by ShawnPR1** [minecrafter/SuperbVote#47]
Hi there. I have an issue with the Vote Reminder where I set the vote-reminder: repeat to 604800 but it still sends the reminder once every 3 or so minutes.

It's supposed to repeat once every week because we can't disable it for some reason. Is there any way I can disable it at all?

Right now I can't even get it to only show once every week. It spams every 3 minutes.

**EDIT**
Upon restarting the server it seems the repeat has taken effect. Strange that the reload command doesn't help.

I would still like to be able to completely disable this. Would setting repeat to -1 or 0 disable it?

**Comment by astei** [comment]
This is such a common question that it's covered on the [wiki](https://github.com/minecrafter/SuperbVote/wiki/Configuration#on-join--repeat):

> To disable the vote reminder entirely, set `on-join` to `false` and `repeat` to `-1`.

**Comment by ShawnPR1** [comment]
Sorry for posting this btw. I just realised before even coming here you clearly state how to disable the repeat in the wiki. Thanks a mil
