### ISSUE TITLE
Votetop empty on some servers

### ISSUE THREAD

**Issue by AmazedMender16** [minecrafter/SuperbVote#50]
Im running the same database for all servers, One of the servers are showing the entire database. the other one is showing 20% of it and the other one is showing nothing... its completely empty.

Am i doing something wrong here? or is this some kind of weird bug

**Comment by astei** [comment]
You are almost certainly doing something wrong. Can you paste the `config.yml` from all your servers?

**Comment by AmazedMender16** [comment]
Hello,

They are the same on all servers though...
https://pastebin.com/RzEUNC9g

**Comment by astei** [comment]
Are you sure about that? No matter the case, SuperbVote will execute the same database commands, it doesn't change from server-to-server (except in one case, finding players for vote reminders).

I have a hard time believing SuperbVote is at fault here.

**Comment by AmazedMender16** [comment]
Hmmm, Yeah im sure they have all the same config and same DB when i check the votes using /sv votes player the votes are the same in all servers. but the command /sv top doesnt show it correctly...
See screenshots:
S1: http://prntscr.com/jpns0z
S2: http://prntscr.com/jpns85
S3: http://prntscr.com/jpnsf5
S4: http://prntscr.com/jpnsje

**Comment by AmazedMender16** [comment]
Anything yet? Its seems to change day by day. Now more servers are showing nothing!

**Comment by astei** [comment]
I have nothing to work with here - I am certain that this can't be a SuperbVote issue. Without learning more about your setup, I can't actually do anything for you.

I'm also limited on time. I recently got into some other projects which are using most of my time.

**Comment by astei** [comment]
I found a related issue with better detail: https://www.spigotmc.org/threads/superbvote.89075/page-37#post-3022502

Looks like this is your issue. Reopening this issue.

**Comment by AmazedMender16** [comment]
May this explains a little?
https://pastebin.com/BLtKaVLL

**Comment by astei** [comment]
Yes, that's it.

I'll try my fix when I've got some free time.

**Comment by AmazedMender16** [comment]
When using the /sv pastetop 

Some users are shown as "null" the users seem to look good in the database though!

Regards,

**Comment by astei** [comment]
That's related to this issue (fixed but not yet tested), but I removed the `pastetop` command for 0.5.

**Comment by AmazedMender16** [comment]
Shooot rip!

Loved that feature ;/ It was pretty handy!
