### ISSUE TITLE
chance-percentage broken!

### ISSUE THREAD

**Issue by bobdabiulder** [minecrafter/SuperbVote#51]
> - if:
>      
>  chance-pecentage: 5
> 
>     commands:
> 
>     - give %player% diamond 3
> 
>     - eco give %player% 250
> 
>     player-message: "&aThanks for meeting nearly impossible conditions, you have been rewarded with 3 diamonds and $250."
> 
>     broadcast-message: "&a%player% got really lucky and was rewarded with 3 diamonds and $250!"

This one is first in my list, and it always runs.

**Comment by astei** [comment]
You misspelled `chance-percentage`.
