### ISSUE TITLE
Placeholderapi

### ISSUE THREAD

**Issue by AmazedMender16** [minecrafter/SuperbVote#52]
Not sure if it has to do with the new placeholderapi updates but after 2.9.1 featherboard has issues with reading the superbvote placeholders!

Regards,

**Comment by astei** [comment]
This is unlikely to be a SuperbVote issue. Please update MVdWPlaceholderAPI.

**Comment by AmazedMender16** [comment]
Not using MVdWPlaceholderAPI for superbvotes placeholders. But will report it on featherboard..

**Comment by AmazedMender16** [comment]
@astei placeholders for MVdWPlaceholderAPI are also broken..

**Comment by astei** [comment]
This is already fixed - please update your SuperbVote placeholder in PlaceholderAPI.

**Comment by AmazedMender16** [comment]
Hello, i'm running the expansion version 1.2.0.. I believe this is the latest..

**Comment by astei** [comment]
I'm not sure what the issue is then. Make sure you're running the latest version of SuperbVote.

**Comment by AmazedMender16** [comment]
Running the latest versions of everything that is available for download....

**Comment by astei** [comment]
Then I'm not sure what I can do for you.

**Comment by AmazedMender16** [comment]
Well is it working correct for you??

**Comment by astei** [comment]
It has been working fine for me.
